// This file is auto-generated by @hey-api/openapi-ts

export const CreateUserDtoSchema = {
    properties: {
        username: {
            type: 'string'
        },
        password: {
            type: 'string'
        },
        isAdmin: {
            type: 'boolean'
        }
    },
    required: ['isAdmin', 'password', 'username'],
    type: 'object'
} as const;

export const RaceSchema = {
    properties: {
        id: {
            type: 'number'
        },
        startTime: {
            format: 'date-time',
            type: 'string'
        },
        scheduledBy: {
            '$ref': '#/components/schemas/User'
        },
        horses: {
            items: {
                '$ref': '#/components/schemas/Horse'
            },
            type: 'array'
        }
    },
    required: ['horses', 'id', 'scheduledBy', 'startTime'],
    type: 'object'
} as const;

export const UserSchema = {
    properties: {
        id: {
            type: 'number'
        },
        username: {
            type: 'string'
        },
        password: {
            type: 'string'
        },
        isAdmin: {
            type: 'boolean'
        },
        isSuspended: {
            type: 'boolean'
        },
        signupDate: {
            format: 'date-time',
            type: 'string'
        },
        horses: {
            items: {
                '$ref': '#/components/schemas/Horse'
            },
            type: 'array'
        },
        scheduledRaces: {
            items: {
                '$ref': '#/components/schemas/Race'
            },
            type: 'array'
        }
    },
    required: ['horses', 'id', 'isAdmin', 'isSuspended', 'password', 'scheduledRaces', 'signupDate', 'username'],
    type: 'object'
} as const;

export const HorseSchema = {
    properties: {
        id: {
            type: 'number'
        },
        name: {
            type: 'string'
        },
        race_count: {
            type: 'number'
        },
        speedRating: {
            type: 'number'
        },
        color: {
            type: 'string'
        },
        retired: {
            type: 'boolean'
        },
        owner: {
            '$ref': '#/components/schemas/User'
        },
        currentRace: {
            '$ref': '#/components/schemas/Race'
        },
        races: {
            items: {
                '$ref': '#/components/schemas/Race'
            },
            type: 'array'
        }
    },
    required: ['color', 'currentRace', 'id', 'name', 'owner', 'race_count', 'races', 'retired', 'speedRating'],
    type: 'object'
} as const;

export const UpdateUserDtoSchema = {
    properties: {},
    type: 'object'
} as const;

export const CreateHorseDtoSchema = {
    properties: {
        name: {
            type: 'string'
        },
        speedRating: {
            type: 'number'
        },
        color: {
            type: 'string'
        },
        ownerId: {
            type: 'number'
        }
    },
    required: ['name', 'ownerId', 'speedRating'],
    type: 'object'
} as const;

export const UpdateHorseDtoSchema = {
    properties: {},
    type: 'object'
} as const;

export const CreateRaceDtoSchema = {
    properties: {
        startTime: {
            format: 'date-time',
            type: 'string'
        },
        horseIds: {
            items: {
                type: 'number'
            },
            type: 'array'
        }
    },
    required: ['startTime'],
    type: 'object'
} as const;

export const UpdateRaceDtoSchema = {
    properties: {},
    type: 'object'
} as const;