/* tslint:disable */
/* eslint-disable */
/**
 * Horse Races
 * Horse Races api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRaceDto
 */
export interface CreateRaceDto {
    /**
     * 
     * @type {Date}
     * @memberof CreateRaceDto
     */
    startTime: Date;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateRaceDto
     */
    horseIds?: Array<number>;
}

/**
 * Check if a given object implements the CreateRaceDto interface.
 */
export function instanceOfCreateRaceDto(value: object): value is CreateRaceDto {
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    return true;
}

export function CreateRaceDtoFromJSON(json: any): CreateRaceDto {
    return CreateRaceDtoFromJSONTyped(json, false);
}

export function CreateRaceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRaceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'startTime': (new Date(json['startTime'])),
        'horseIds': json['horseIds'] == null ? undefined : json['horseIds'],
    };
}

  export function CreateRaceDtoToJSON(json: any): CreateRaceDto {
      return CreateRaceDtoToJSONTyped(json, false);
  }

  export function CreateRaceDtoToJSONTyped(value?: CreateRaceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'startTime': ((value['startTime']).toISOString()),
        'horseIds': value['horseIds'],
    };
}

